name: Android CI

on:
  push:
    branches: [ lsp ]
  pull_request:
    branches: [ lsp ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew buildDebug
    - name: Upload Debug artifact
    - uses: actions/upload-artifact@v2
      with:
        name: lspatch-debug
        path: out/
        
    - name: Build with Gradle
      run: ./gradlew buildRelease
    - name: Upload Release artifact
    - uses: actions/upload-artifact@v2
      with:
        name: lspatch-release
        path: out/
